# Generated by Django 5.0.6 on 2024-05-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(default="default.jpg", upload_to="users/%Y/%m/%d"),
        ),
    ]
